CREATE TABLE IF NOT EXISTS prediction_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_uuid CHAR(36) NOT NULL,
    recommendation_date DATE NOT NULL,
    starttime DATE NOT NULL,
    endtime DATE NOT NULL,
    lookback_days INT NOT NULL,
    pred_len INT NOT NULL,
    min_history_points INT NOT NULL,
    max_context INT NOT NULL,
    context_length INT NULL,
    model_name VARCHAR(128) NOT NULL,
    tokenizer_name VARCHAR(128) NOT NULL,
    device VARCHAR(64) NULL,
    temperature DECIMAL(10, 6) NOT NULL,
    top_p DECIMAL(10, 6) NOT NULL,
    sample_count INT NOT NULL,
    inference_verbose TINYINT(1) NOT NULL DEFAULT 0,
    stock_count_raw INT NOT NULL DEFAULT 0,
    stock_count_dedup INT NOT NULL DEFAULT 0,
    stock_count_success INT NOT NULL DEFAULT 0,
    stock_count_failed INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    error_message TEXT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_prediction_runs_run_uuid (run_uuid),
    KEY idx_prediction_runs_recommendation_date (recommendation_date),
    KEY idx_prediction_runs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_predictions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT UNSIGNED NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    history_start_date DATE NOT NULL,
    history_end_date DATE NOT NULL,
    prediction_date DATE NOT NULL,
    pred_open DECIMAL(18, 6) NOT NULL,
    pred_high DECIMAL(18, 6) NOT NULL,
    pred_low DECIMAL(18, 6) NOT NULL,
    pred_close DECIMAL(18, 6) NOT NULL,
    pred_volume DECIMAL(18, 6) NOT NULL,
    pred_amount DECIMAL(18, 6) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_predictions_run_id FOREIGN KEY (run_id) REFERENCES prediction_runs (id),
    KEY idx_stock_predictions_run_stock_date (run_id, stock_code, prediction_date),
    KEY idx_stock_predictions_stock_code (stock_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backtest_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_uuid CHAR(36) NOT NULL,
    recommendation_date DATE NOT NULL,
    backtest_start_date DATE NOT NULL,
    backtest_end_date DATE NOT NULL,
    pred_len INT NOT NULL,
    candidate_context_lengths TEXT NOT NULL,
    success_mape_threshold DECIMAL(10, 6) NOT NULL,
    best_context_length INT NULL,
    best_success_rate DECIMAL(10, 6) NULL,
    total_sample_count INT NOT NULL DEFAULT 0,
    total_result_count INT NOT NULL DEFAULT 0,
    csv_summary_path VARCHAR(255) NULL,
    csv_detail_path VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL,
    error_message TEXT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_backtest_runs_run_uuid (run_uuid),
    KEY idx_backtest_runs_dates (backtest_start_date, backtest_end_date),
    KEY idx_backtest_runs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backtest_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键 ID',
    backtest_run_id BIGINT UNSIGNED NOT NULL COMMENT '关联 backtest_runs.id 的回测运行 ID',
    stock_code VARCHAR(16) NOT NULL COMMENT '股票代码',
    evaluation_date DATE NOT NULL COMMENT '回测评估日期，即使用该日期及之前历史数据进行预测',
    context_length INT NOT NULL COMMENT '本次回测使用的历史上下文长度',
    history_start_date DATE NOT NULL COMMENT '本次样本历史窗口起始日期',
    history_end_date DATE NOT NULL COMMENT '本次样本历史窗口结束日期',
    baseline_close DECIMAL(18, 6) NOT NULL COMMENT '评估基准收盘价，通常为历史窗口最后一个交易日收盘价',
    prediction_date_1 DATE NOT NULL COMMENT '第 1 个预测交易日日期',
    prediction_date_2 DATE NOT NULL COMMENT '第 2 个预测交易日日期',
    prediction_date_3 DATE NOT NULL COMMENT '第 3 个预测交易日日期',
    pred_open_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日预测开盘价',
    pred_open_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日预测开盘价',
    pred_open_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日预测开盘价',
    pred_high_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日预测最高价',
    pred_high_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日预测最高价',
    pred_high_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日预测最高价',
    pred_low_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日预测最低价',
    pred_low_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日预测最低价',
    pred_low_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日预测最低价',
    pred_close_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日预测收盘价',
    pred_close_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日预测收盘价',
    pred_close_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日预测收盘价',
    pred_volume_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日预测成交量',
    pred_volume_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日预测成交量',
    pred_volume_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日预测成交量',
    pred_amount_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日预测成交额',
    pred_amount_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日预测成交额',
    pred_amount_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日预测成交额',
    actual_close_1 DECIMAL(18, 6) NOT NULL COMMENT '第 1 个预测交易日实际收盘价',
    actual_close_2 DECIMAL(18, 6) NOT NULL COMMENT '第 2 个预测交易日实际收盘价',
    actual_close_3 DECIMAL(18, 6) NOT NULL COMMENT '第 3 个预测交易日实际收盘价',
    day3_mape DECIMAL(10, 6) NOT NULL COMMENT '第 3 个预测交易日收盘价 MAPE',
    close_mae DECIMAL(18, 6) NOT NULL COMMENT '三天预测收盘价 MAE',
    close_rmse DECIMAL(18, 6) NOT NULL COMMENT '三天预测收盘价 RMSE',
    direction_correct TINYINT(1) NOT NULL COMMENT '第 3 个预测交易日涨跌方向是否预测正确',
    is_success TINYINT(1) NOT NULL COMMENT '本条回测结果是否满足成功标准',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    CONSTRAINT fk_backtest_results_run_id FOREIGN KEY (backtest_run_id) REFERENCES backtest_runs (id),
    KEY idx_backtest_results_run_context (backtest_run_id, context_length),
    KEY idx_backtest_results_stock_date (stock_code, evaluation_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回测结果明细表，保存每只股票、每个评估日的三日预测结果与评估指标';
